name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PLATFORMIO_PKG_DOWNLOAD_TIMEOUT: 600
      PIO_HOME_DIR: ~/.platformio

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            .pio
          key: pio-${{ runner.os }}-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            pio-${{ runner.os }}-

      - name: Install PlatformIO Core
        run: |
          python -m pip install -U pip
          pip install -U platformio

      # Pre-install platform espressif32 đúng version để tránh UnknownPackageError
      - name: Preinstall espressif32 platform
        run: |
          pio pkg update -g || true
          pio platform install espressif32@6.9.0
          pio platform list

      - name: Build (esp32s3)
        run: pio run -e esp32s3 -v