- name: Cache PlatformIO
  uses: actions/cache@v4
  with:
    path: |
      ~/.platformio
      .pio
    key: pio-${{ runner.os }}-${{ hashFiles('**/platformio.ini') }}
    restore-keys: |
      pio-${{ runner.os }}-

- name: Install PlatformIO Core
  run: |
    python -m pip install -U pip
    pip install -U platformio

- name: Preinstall espressif32 platform
  run: |
    pio pkg update -g || true
    pio platform install espressif32@6.9.0
    pio platform list

- name: Clean & Build
  run: |
    pio run -e esp32s3 -t clean
    pio run -e esp32s3 -v