name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PLATFORMIO_PKG_DOWNLOAD_TIMEOUT: 600
      PIO_HOME_DIR: ~/.platformio

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache PlatformIO packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            .pio
          key: pio-${{ runner.os }}-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            pio-${{ runner.os }}-

      - name: Install PlatformIO Core
        run: |
          python -m pip install -U pip
          pip install -U platformio

      # Quan trọng: preinstall để tránh UnknownPackageError trên CI
      - name: Preinstall espressif32 toolchains & framework
        run: |
          pio pkg update -g
          # Lock phiên bản platform (ổn định)
          pio platform install espressif32@6.9.0
          # Nếu dùng Arduino, preinstall luôn framework (tùy code của bạn)
          pio pkg install -g --platform espressif32 --framework arduino
          # Nếu code dùng ESP-IDF, đổi dòng trên thành:
          # pio pkg install -g --platform espressif32 --framework espidf

      - name: Build (all envs)
        run: pio run -v